### ISSUE TITLE
Понизить minSdkVersion

### ISSUE THREAD

**Issue by ddrozdov** [vtr0n/react-native-yandex-mobile-ads#11]
Если это возможно, просьба понизить minSdkVersion до 21.

**Comment by valery-lavrik** [comment]
вот что сделай:

в файл AndroidManifest.xml  
добавь
`xmlns:tools="http://schemas.android.com/tools"`
и
`<uses-sdk android:minSdkVersion="24" android:targetSdkVersion="31" tools:overrideLibrary="com.reactnativeyandexmobileads" />`

чтоб получилось вот так:
![image](https://user-images.githubusercontent.com/8047999/203714757-67c1d285-c615-4143-a8ae-ed0aad492415.png)

**Comment by bezgodov** [comment]
Другой вариант — добавить в `app.json` (не забываем установить зависимость `npx expo install expo-build-properties`)

```json
"plugins": [
  [
    "expo-build-properties",
    {
      "android": {
        "minSdkVersion": 24
      }
    }
  ]
]
```
