### ISSUE TITLE
Didn't find class AdSize

### ISSUE THREAD

**Issue by atantsyra** [vtr0n/react-native-yandex-mobile-ads#20]
Ошибка при попытке отображения баннера.
```javascript
"react-native": "0.71.11",
"react-native-yandex-mobile-ads": "^0.8.0",
``` 
<img width="440" alt="Error while updating property 'size' of a view" src="https://github.com/vtr0n/react-native-yandex-mobile-ads/assets/120718362/89bb4372-6a4a-4184-808c-527b4a33a247">
ошибка где-то здесь BannerView.java import 
com.yandex.mobile.ads.banner.AdSize;
```
 <BannerView
    key={key}
    adUnitId={banner.unitId}
    size="BANNER_320x50"
 />
```

**Comment by vtr0n** [comment]
Должно было пофикситься в 0.9.1
