### ISSUE TITLE
Native Ads

### ISSUE THREAD

**Issue by renatomserra** [vtr0n/react-native-yandex-mobile-ads#24]
Hellow!

Thank you for building this package.
Im exploring yandex ads atm, any plan to support native ads? the ones where you can create your own design.

Thank you
Renato

**Comment by vtr0n** [comment]
Hey!
Unfortunately, there are no plans to develop this package yet. This is an unofficial repository, I try to keep the latest versions, but not the new functionality.

**Comment by renatomserra** [comment]
thank you, i appreciate it :)
