### ISSUE TITLE
iOS Yandex Ads Version error

### ISSUE THREAD

**Issue by LevanKvirkvelia** [vtr0n/react-native-yandex-mobile-ads#7]
Кажется тут ошибка, поэтому устанавливается не последняя версия

https://github.com/vtr0n/react-native-yandex-mobile-ads/blob/ce59a26de927a0479f82367a8a5dc9b2af105ffc/react-native-yandex-mobile-ads.podspec#L19

**Comment by vtr0n** [comment]
Спасибо, поправил
